apiVersion: apps/v1
kind: Deployment
metadata:
  name: acrdemo-localdocker-deployment
  labels:
    app: acrdemo-localdocker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: acrdemo-localdocker
  template:
    metadata:
      labels:
        app: acrdemo-localdocker
    spec:
      containers:
        - name: ACRforCapstone
          image: capstoneacr.azurecr.io/springbootapp
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: springbootapp

   
