apiVersion: apps/v1
kind: Deployment
metadata:
  name: capstone-app-deploy
  labels:
    app: capstone-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: capstone-app
  template:
    metadata:
      labels:
        app: capstone-app
    spec:
      containers:
        - name: capstone-app
          image: capstoneacr123.azurecr.io/capstone-container
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: springbootapp
---
apiVersion: v1
kind: Service
metadata:
  name: capstone-app-service
  labels:
    app: capstone-app
spec:
  type: LoadBalancer
  selector:
    app: capstone-app
  ports:
    - port: 80
      targetPort: 8080

  readinessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5

  livenessProbe:
    httpGet:
      path: /
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 5

  startupProbe:
    httpGet:
      path: /
      port: 8080
    failureThreshold: 30
    periodSeconds: 5


---
apiVersion: v1
kind: Service
metadata:
  name: capstone-app-service
  labels:
    app: capstone-app
spec:
  type: LoadBalancer
  selector:
    app: capstone-app
  ports:
    - port: 80
      targetPort: 8080

